name: Executar Busca Manual
on:
  schedule:
    - cron: '0 */6 * * *' 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: pip install google-genai google-search-results jinja2
        
      - name: Run Search Engine
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SERP_API_KEY: ${{ secrets.SERP_API_KEY }}
        run: python "Search Engine.py"
        
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          # AQUI ESTAVA O ERRO: Alteramos para index.html
          git add index.html
          git commit -m "Painel atualizado: $(date)" || echo "Sem mudanças"
          git push
